requires 'Class::Accessor::Fast';
requires 'File::Basename';
requires 'File::Spec';
requires 'File::Temp';
requires 'IO::Socket::SSL', '!= 1.38';
requires 'JSON::MaybeXS';
requires 'LWP::Protocol::https';
requires 'LWP::UserAgent', '5.813';
requires 'Test::More';
requires 'URI';
requires 'URI::Escape';
requires 'YAML';
recommends 'Term::ANSIColor';
recommends 'Term::ShellUI';
